#ifndef _KEYMAP_H
#define _KEYMAP_H

#define PLAYER_1_MOVE_UP	SDL_SCANCODE_UP
#define PLAYER_1_MOVE_DOWN	SDL_SCANCODE_DOWN 
#define PLAYER_1_MOVE_LEFT	SDL_SCANCODE_LEFT
#define PLAYER_1_MOVE_RIGHT	SDL_SCANCODE_RIGHT
#define PLAYER_1_SHOOT		SDL_SCANCODE_RCTRL
#define PLAYER_1_USE		SDL_SCANCODE_RALT

#define PLAYER_2_MOVE_UP	SDL_SCANCODE_W
#define PLAYER_2_MOVE_DOWN	SDL_SCANCODE_S
#define PLAYER_2_MOVE_LEFT	SDL_SCANCODE_A
#define PLAYER_2_MOVE_RIGHT	SDL_SCANCODE_D
#define PLAYER_2_SHOOT		SDL_SCANCODE_F
#define PLAYER_2_USE		SDL_SCANCODE_G

#endif
